# -*- coding: utf-8 -*-
"""sentiment analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/189y5BtWfbWRdTHt6NyxrDYOL8-VUQsxt
"""

pip install flair

from datetime import datetime
import requests
import pandas as pd
import seaborn as sns

BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAALxdMQEAAAAAQLauISsmwNTTuOUiyjIY9Snq0JE%3DAM4UuquXRQvENnoZ6MCtSuAZws71IOWzApcPa1kWYInJwsQEJP'

params = {'q': 'gme',
          'tweet_mode': 'extended',
          'lang': 'en',
          'count': '100'}
response=requests.get('https://api.twitter.com/1.1/search/tweets.json',params=params,
             headers={'authorization': 'Bearer '+BEARER_TOKEN})

print(response.json())

def get_data(tweet):
  data = {
      'id': tweet['id_str'],
      'created_at': tweet['created_at'],
      'text': tweet['full_text']
  }
  return data

df = pd.DataFrame()
for tweet in response.json()['statuses']:
  row = get_data(tweet)
  df = df.append(row, ignore_index=True)

tweets = df['text']
txts = tweets.to_list()

import flair
sentiment_model = flair.models.TextClassifier.load('en-sentiment')

values = []
confidence = []
for txt in txts:
  sentence = flair.data.Sentence(txt)
  sentiment_model.predict(sentence)
  v = sentence.labels[0].to_dict()['value']
  c = sentence.labels[0].to_dict()['confidence']
  values.append(v)
  confidence.append(c)

df['values'] = values
df['confidence'] = confidence

df.head(10)

df.groupby(by='values').agg('count')

sns.displot(df,x='values',hue='values')